---
- name: Safely patch Kubernetes node OS
  hosts: all
  serial: 1
  become: true

  vars:
    kubeconfig: /tmp/admin.conf
    reboot_required_file: /var/run/reboot-required
    drain_timeout: 600

  pre_tasks:
    - name: Get node name
      command: hostname
      register: node_name
      changed_when: false

  tasks:
    # ===============================
    # Worker nodes – cordon & drain
    # ===============================
    - name: Cordon worker node
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      command: kubectl cordon {{ node_name.stdout }}
      when: inventory_hostname in groups['kube_node']

    - name: Drain worker node
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      command: >
        kubectl drain {{ node_name.stdout }}
        --ignore-daemonsets
        --delete-emptydir-data
        --force
        --timeout={{ drain_timeout }}s
      when: inventory_hostname in groups['kube_node']

    # ===============================
    # OS patching
    # ===============================
    - name: Update OS packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if reboot is required
      stat:
        path: "{{ reboot_required_file }}"
      register: reboot_required

    - name: Reboot node if required
      reboot:
        reboot_timeout: 900
      when: reboot_required.stat.exists

    # ===============================
    # Wait for node readiness
    # ===============================
    - name: Wait for kube-apiserver to be reachable (control plane)
      when: inventory_hostname in groups['kube_control_plane']
      wait_for:
        host: 127.0.0.1
        port: 6443
        delay: 10
        timeout: 300

    - name: Wait for worker node to become Ready
      when: inventory_hostname in groups['kube_node']
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      command: >
        kubectl wait node/{{ node_name.stdout }}
        --for=condition=Ready
        --timeout=600s

    # ===============================
    # Worker nodes – uncordon
    # ===============================
    - name: Uncordon worker node
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
      command: kubectl uncordon {{ node_name.stdout }}
      when: inventory_hostname in groups['kube_node']

