[all:vars]
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
[all]
test-cp1 ansible_host=172.168.122.111 ansible_user=ubuntu
test-cp2 ansible_host=172.168.122.112 ansible_user=ubuntu
test-cp3 ansible_host=172.168.122.113 ansible_user=ubuntu
[kube_control_plane]
test-cp1
test-cp2
test-cp3
[etcd:children]
kube_control_plane

[kube_node]
